#!/bin/bash
# On-device per-unit stamping. Pushed and run as root by stamp/stamp_unit.sh.
# Sets the unit's identity: hostname, ROS_DOMAIN_ID, and the udev symlinks
# /dev/rplidar + /dev/wave_rover from the CP2102N chip serials. Idempotent.
#
# Env (all provided by stamp_unit.sh):
#   HOSTNAME_NEW           hostname to set
#   DOMAIN_ID              ROS_DOMAIN_ID (written to /etc/qb3rt/domain_id)
#   USB_RPLIDAR_SERIAL     CP2102N serial -> /dev/rplidar
#   USB_WAVE_ROVER_SERIAL  CP2102N serial -> /dev/wave_rover
set -euo pipefail

: "${HOSTNAME_NEW:?}" "${DOMAIN_ID:?}"

echo "== Hostname -> ${HOSTNAME_NEW} =="
CUR="$(hostnamectl --static 2>/dev/null || cat /etc/hostname)"
if [ "$CUR" != "$HOSTNAME_NEW" ]; then
    hostnamectl set-hostname "$HOSTNAME_NEW"
    # keep /etc/hosts 127.0.1.1 line consistent (avoids sudo name-resolution warns)
    if grep -qE '^\s*127\.0\.1\.1' /etc/hosts; then
        sed -i -E "s/^(\s*127\.0\.1\.1\s+).*/\1${HOSTNAME_NEW}/" /etc/hosts
    else
        printf '127.0.1.1\t%s\n' "$HOSTNAME_NEW" >> /etc/hosts
    fi
    echo "  set (was ${CUR})"
else
    echo "  already ${HOSTNAME_NEW}"
fi

echo "== ROS_DOMAIN_ID -> ${DOMAIN_ID} =="
mkdir -p /etc/qb3rt
echo "$DOMAIN_ID" > /etc/qb3rt/domain_id

echo "== USB serial udev symlinks =="
RULES=/etc/udev/rules.d/99-agv-serial.rules
if [ -n "${USB_RPLIDAR_SERIAL:-}" ] && [ -n "${USB_WAVE_ROVER_SERIAL:-}" ]; then
    cat > "$RULES" <<EOF
# Generated by stamp/stamp_unit.sh for ${HOSTNAME_NEW} — do not hand-edit.
# Both adapters are Silicon Labs CP2102N (10c4:ea60); pin stable names by serial.
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="${USB_RPLIDAR_SERIAL}", SYMLINK+="rplidar"
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="${USB_WAVE_ROVER_SERIAL}", SYMLINK+="wave_rover"
EOF
    udevadm control --reload-rules
    udevadm trigger --subsystem-match=tty || true
    echo "  rplidar=${USB_RPLIDAR_SERIAL} wave_rover=${USB_WAVE_ROVER_SERIAL}"
else
    echo "  WARNING: USB serials not both set — skipping udev (set them in the unit profile)." >&2
fi

echo "== Static IP -> ${STATIC_IP:-<keep DHCP>} =="
if [ -n "${STATIC_IP:-}" ]; then
    # Pin the active Wi-Fi connection to a fixed address. Applied to the netplan/
    # NM connection now, but re-activated a few seconds AFTER this SSH session
    # closes — switching the IP live would sever the very connection we're on.
    conn="$(nmcli -t -f NAME,TYPE connection show --active 2>/dev/null | awk -F: '$2=="802-11-wireless"{print $1; exit}')"
    if [ -z "$conn" ]; then
        echo "  WARNING: no active Wi-Fi connection to pin — skipping static IP." >&2
    else
        gw="${GATEWAY:-${STATIC_IP%.*}.1}"
        nmcli connection modify "$conn" \
            ipv4.method manual ipv4.addresses "${STATIC_IP}/${PREFIX:-24}" \
            ipv4.gateway "$gw" ipv4.dns "${DNS:-$gw}"
        echo "  $conn -> ${STATIC_IP}/${PREFIX:-24} gw $gw (switches ~3s after this session ends)"
        systemd-run --on-active=3 --unit=qb3rt-ipswitch nmcli connection up "$conn" >/dev/null 2>&1 \
            || ( nohup sh -c "sleep 3; nmcli connection up '$conn'" >/dev/null 2>&1 & )
    fi
fi

echo "Stamp done for ${HOSTNAME_NEW} (domain ${DOMAIN_ID})."
